[ERROR] 2021-03-11 21:26:23,996 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-03-11 21:26:23.465911-10.0.2.2-d43
[ERROR] 2021-03-11 21:29:46,107 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-03-11 21:29:46.054191-10.0.2.2-ac2
[ERROR] 2021-03-11 21:30:20,551 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-03-11 21:30:20.501346-10.0.2.2-b97
