[ERROR] 2021-03-11 21:25:47,686 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-03-11 21:25:47.198218-10.0.2.2-db3
